# Generated by Django 3.2.6 on 2021-08-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
