# Generated by Django 3.2.6 on 2021-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Not free', 'Not free'), ('Go Dutch', 'Go Dutch')], default='Free', max_length=8),
        ),
    ]
