# Generated by Django 3.2.6 on 2021-08-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210811_1613'),
        ('events', '0008_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('att_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appreciation_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='None', max_length=4)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attended_evets', to='accounts.profile')),
            ],
        ),
    ]
