# Generated by Django 3.2.6 on 2021-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'Concert'), ('Food', 'Food'), ('Party', 'Party'), ('Sport', 'Sport'), ('Study', 'Study')], default='Else', max_length=7),
        ),
    ]
