# Generated by Django 3.2.6 on 2021-08-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_event_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='profile',
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attended_evets', to=settings.AUTH_USER_MODEL),
        ),
    ]
