# Generated by Django 3.2.6 on 2021-08-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_attendee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
