# Generated by Django 3.2.6 on 2021-08-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20210817_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
