# Generated by Django 3.2.6 on 2021-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20210818_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_num_of_attendees',
            field=models.IntegerField(default=0),
        ),
    ]
