# Generated by Django 3.2.6 on 2021-08-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_event_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_picture',
        ),
    ]
