# Generated by Django 3.2.6 on 2021-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_event_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default=None, upload_to='static/uploads/event/'),
        ),
    ]
