# Generated by Django 3.2.6 on 2021-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, default=None, upload_to='static/uploads/events/'),
        ),
    ]
