# Generated by Django 3.2.6 on 2021-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_event_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/events/'),
        ),
    ]
