# Generated by Django 3.2.6 on 2021-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciation_level',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
