# Generated by Django 3.2.6 on 2021-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_attendee_appreciation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciation_level',
            field=models.IntegerField(default=0),
        ),
    ]
