# Generated by Django 3.2.6 on 2021-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_attendee_appreciation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciation_level',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
