# Generated by Django 3.2.6 on 2021-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_attendee_appreciation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciation_level',
            field=models.CharField(blank=True, default='0', max_length=1),
        ),
    ]
