# Generated by Django 3.2.6 on 2021-09-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_attendee_appreciation_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='appreciated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 15, 28, 11, 637849), null=True),
        ),
    ]
