# Generated by Django 3.2.6 on 2021-09-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_attendee_appreciated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 15, 29, 54, 787558), null=True),
        ),
    ]
