# Generated by Django 3.2.6 on 2021-09-06 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_alter_attendee_appreciated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 6, 11, 56, 1, 853131), null=True),
        ),
    ]
