# Generated by Django 3.2.6 on 2021-09-09 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_alter_attendee_appreciated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='appreciated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 9, 14, 51, 31, 590635), null=True),
        ),
    ]
