# Generated by Django 3.2.6 on 2021-08-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Concert', 'Concert'), ('Food', 'Food'), ('Party', 'Party'), ('Sport', 'Sport'), ('Study', 'Study')], default='Else', max_length=10)),
            ],
        ),
    ]
