# Generated by Django 3.2.6 on 2021-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='-', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Do not want to specify', 'Do not want to specify'), ('Male', 'Male'), ('Female', 'Female')], default='Do not want to specify', max_length=22),
        ),
    ]
