# Generated by Django 3.2.6 on 2021-08-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='-', max_length=22),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='-', max_length=22),
        ),
    ]
