# Generated by Django 3.2.6 on 2021-08-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_likedevent_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
