# Generated by Django 3.2.6 on 2021-08-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
