# Generated by Django 3.2.6 on 2021-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://bootdey.com/img/Content/avatar/avatar2.png', upload_to='static/uploads/'),
        ),
    ]
