# Generated by Django 3.2.6 on 2021-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_alter_attendee_appreciated_at'),
        ('accounts', '0020_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommendations',
            field=models.ManyToManyField(null=True, related_name='recommended_to_profile', to='events.Event'),
        ),
    ]
